### ISSUE TITLE
[1.14.4] Stacktrace in log- With latest forge 1.0.6 post release build.

### ISSUE THREAD

**Issue by ProsperCraft** [xfl03/MoreCrashInfo#1]
I think this needs an update to latest forge 1.0.6

Error occurred applying transform of coremod crashtransformers.js function CrashMakerTransformer

https://gist.github.com/ProsperCraft/32e1981d4130779dd16333f4d616c68d

**Comment by ProsperCraft** [comment]
Here is another one with Forge forge-1.14.4-28.1.39

https://gist.github.com/ProsperCraft/098e2d34e2c171598d60a80bee92a66b

**Comment by xfl03** [comment]
Sorry about not seen this issue at the first time.
It has been fixed.
