### ISSUE TITLE
[Feature Request] 支持 Mixin

### ISSUE THREAD

**Issue by ZekerZhayard** [xfl03/MoreCrashInfo#2]
随着 [MixinBootstrap](https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap) 自 forge-1.14.4-28.0.45 以来被广泛应用，以及 Mixin 本体自 forge-1.15.2-31.2.44 / forge-1.16.1-32.0.72 以来被内置进了 forge 的运行库中，越来越多的 Core Mod 开始抛弃 JavaScript 转而使用 Mixin。
尽管 Mixin 自己内部有一套相对完善的冲突报错机制，但是体现到崩溃报告中仅能指示 mixin json，有的时候会很难找到这个 json 对应的 jar 在哪。
因此我建议这个 mod 简单支持一下 Mixin

**Comment by xfl03** [comment]
https://github.com/xfl03/MoreCrashInfo/commit/0b23151941ec7d6f0612b12276d02bf45c744466
